import java.util.regex.Matcher
import java.util.regex.Pattern

plugins {
    id 'java-library'
    id 'maven-publish'
    id 'signing'
    id 'dev.lukebemish.immaculate'
}

base {
    archivesName = "${mod_id}-${project.name}-${minecraft_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    withSourcesJar()
    withJavadocJar()
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = 'Parchment'
                url = 'https://maven.parchmentmc.org'
            }
        }
        filter { includeGroupAndSubgroups("org.parchmentmc") }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = 'Fabric'
                url = 'https://maven.fabricmc.net/'
            }
        }
        filter { includeGroupAndSubgroups("net.fabricmc") }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = 'Mod Menu'
                url = 'https://maven.terraformersmc.com/releases'
            }
        }
        filter {
            includeGroupAndSubgroups "com.terraformersmc"
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = 'Modrinth'
                url = 'https://api.modrinth.com/maven'
            }
        }
        filter { includeGroupAndSubgroups "maven.modrinth" }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = 'JEI'
                url = 'https://maven.blamejared.com/'
            }
        }
        filter { includeGroupAndSubgroups "mezz.jei" }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = 'Sponge'
                url = 'https://repo.spongepowered.org/repository/maven-public'
            }
        }
        filter { includeGroupAndSubgroups("org.spongepowered") }
    }
    maven {
        name = 'TommyLib'
        url = 'https://dl.cloudsmith.io/public/thomasglasser/tommylib/maven/'
        content {
            includeGroupAndSubgroups("dev.thomasglasser.tommylib")
        }
    }
    maven {
        name = 'NeoForge'
        url = 'https://maven.neoforged.net/releases'
    }
    maven {
        name = 'Mojang Meta'
        url = 'https://maven.neoforged.net/mojang-meta'
    }
    mavenCentral()
    mavenLocal()
}

// Declare capabilities on the outgoing configurations.
// Read more about capabilities here: https://docs.gradle.org/current/userguide/component_capabilities.html#sec:declaring-additional-capabilities-for-a-local-component
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations."$variant".outgoing {
        capability("$group:${base.archivesName.get()}:$version")
        capability("$group:$mod_id-${project.name}-${minecraft_version}:$version")
        capability("$group:$mod_id:$version")
    }
    publishing.publications.configureEach {
        suppressPomMetadataWarningsFor(variant)
    }
}

jar {
    manifest {
        attributes([
                'Specification-Title'   : mod_name,
                'Specification-Vendor'  : mod_author,
                'Specification-Version' : project.jar.archiveVersion,
                'Implementation-Title'  : project.name,
                'Implementation-Version': project.jar.archiveVersion,
                'Implementation-Vendor' : mod_author,
                'Built-On-Minecraft'    : minecraft_version
        ])
    }
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            version: project.version,
            group: project.group,
            minecraft_version: minecraft_version,
            next_minecraft_version: next_minecraft_version,
            mod_name: mod_name,
            mod_author: mod_author,
            mod_id: mod_id,
            license: license,
            description: project.description,
            neoforge_version: neoforge_version,
            major_fml_version: major_fml_version,
            fabric_version: fabric_version,
            fabric_loader_version: fabric_loader_version,
            java_version: java_version,
            icon: icon,
            github_name: github_name,
            tommylib_version: tommylib_version,
    ]

    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.resources.srcDir generateModMetadata
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
tasks.processResources.dependsOn generateModMetadata

build.dependsOn immaculateCheck

immaculate {
    workflows.register('java') {
        java()
        files.from rootProject.fileTree("src", {
            include "**/*.java"
        })
        noTabs()
        googleFixImports()
        toggleOff = 'spotless:off'
        toggleOn = 'spotless:on'
        eclipse {
            version '3.37.0'
            config = rootProject.file('codeformat/formatter-config.xml')
        }


        // courtesy of diffplug/spotless#240
        // https://github.com/diffplug/spotless/issues/240#issuecomment-385206606
        custom 'noWildcardImports', { String fileContents ->
            if (fileContents.contains('*;\n')) {
                throw new GradleException('No wildcard imports are allowed!')
            }
        }

        custom 'noNotNull', { String fileContents ->
            if (fileContents.contains('@NotNull') || fileContents.contains('@Nonnull')) {
                throw new GradleException('@NotNull and @Nonnull are disallowed.')
            }
        }

        //Trim any trailing whitespace from patch additions
        def trailingWhitespace = Pattern.compile('^\\+.*[ \t]+\$', Pattern.UNIX_LINES | Pattern.MULTILINE)
        custom 'trimTrailingWhitespace', { String fileContents ->
            Matcher matcher = trailingWhitespace.matcher(fileContents)
            StringBuilder sb = new StringBuilder()
            while (matcher.find()) {
                matcher.appendReplacement(sb, matcher.group().trim())
            }
            matcher.appendTail(sb)
            return sb.toString()
        }

        custom 'jetbrainsNullable', { String fileContents ->
            fileContents.replace('javax.annotation.Nullable', 'org.jetbrains.annotations.Nullable')
        }
    }
}

javadoc {
    failOnError = false
    options.tags = [ "apiNote", "reason" ]
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
        }

        maven(MavenPublication) {
            pom {
                name = project.mod_name
                description = project.description
                url = "https://github.com/thomasglasser/${github_name}/wiki"
                licenses {
                    license {
                        name = project.license
                        url = project.license_url
                    }
                }
                developers {
                    developer {
                        id = project.mod_author
                        name = project.mod_author
                    }
                }
                issueManagement {
                    system = 'GitHub'
                    url = "https://github.com/thomasglasser/${github_name}/issues"
                }
                scm {
                    connection = "scm:git:git://github.com/thomasglasser/${github_name}.git"
                    developerConnection = "scm:git:ssh://github.com:thomasglasser/${github_name}.git"
                    url = "https://github.com/thomasglasser/${github_name}/tree/${minecraft_version}"
                }
            }
        }
    }

    repositories {
        maven {
            name = "Cloudsmith"
            url = "https://maven.cloudsmith.io/thomasglasser/${mod_id}/"
            credentials {
                username = project.findProperty("CLOUDSMITH_USERNAME") ?: System.getenv("CLOUDSMITH_USERNAME")
                password = project.findProperty("CLOUDSMITH_API_KEY") ?: System.getenv("CLOUDSMITH_API_KEY")
            }
        }
    }
}

signing {
    useGpgCmd()
    sign publishing.publications
}
