# Project
version=8.0.0
group=dev.thomasglasser.sherdsapi

# Mod Options
mod_name=Sherds API
mod_author=Thomas Glasser
mod_id=sherdsapi
description=Makes adding new pottery sherds easy
license=LGPL-3.0
license_url=https://www.gnu.org/licenses/lgpl-3.0-standalone.html
icon=icon.png
github_name=Sherds-API
java_version=25

# Common
minecraft_version=26.1.2
next_minecraft_version=26.2
mdg_version=2.0.141
neoform_version=1
mixin_version=0.17.0+mixin.0.8.7
mixinextras_version=0.5.3

# Dependencies
tommylib_version=34.0.0

# Runtime
jade_version=26.1.8
jei_version=29.14.0.43

# NeoForge
neoforge_version=26.1.2.78

# Fabric
fabric_version=0.154.2+26.1.2
fabric_loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Runtime
modmenu_version=18.0.0

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
