# Project
version=7.0.0
group=dev.thomasglasser.sherdsapi

# Mod options
mod_name=Sherds API
mod_author=Thomas Glasser
mod_id=sherdsapi
description=Makes adding new pottery sherds easy
license=LGPL-3.0
license_url=https://www.gnu.org/licenses/lgpl-3.0-standalone.html
icon=icon.png
github_name=Sherds-API
java_version=25

# Common
minecraft_version=26.1
next_minecraft_version=26.2
mdg_version=2.0.141
neoform_version=1
mixin_version=0.17.0+mixin.0.8.7
mixinextras_version=0.5.3

# Dependencies
tommylib_version=33.0.0-c

# Runtime
jade_version=26.0.5
jei_version=26.0.0.1

# NeoForge
neoforge_version=26.1.0.7-beta
major_fml_version=11

# Fabric
fabric_version=0.144.3+26.1
fabric_loader_version=0.18.5
loom_version=1.15-SNAPSHOT

# Runtime
modmenu_version=18.0.0-alpha.8

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
