# Project
version=6.1.2
group=dev.thomasglasser.sherdsapi

# Mod options
mod_name=Sherds API
mod_author=Thomas Glasser
mod_id=sherdsapi
description=Makes adding new pottery sherds easy
license=GPL-3.0
license_url=https://www.gnu.org/licenses/gpl-3.0.html
icon=icon.png
github_name=Sherds-API
java_version=21

# Common
minecraft_version=1.21.5
previous_minecraft_version=1.21.4
next_minecraft_version=1.21.6
mdg_version=2.0.80
neoform_version=20250325.162830
mixin_version=0.15.2+mixin.0.8.7
mixinextras_version=0.4.1

# Parchment
parchment_minecraft_version=1.21.4
parchment_version=2025.03.23

# Dependencies
tommylib_version=31.0.0

# Runtime
jade_version=18.1.0
jei_version=19.21.0.247

# NeoForge
neoforge_version=21.5.39-beta
major_fml_version=7

# Fabric
fabric_version=0.120.0+1.21.5
fabric_loader_version=0.16.13
loom_version=1.10.+

# Runtime
modmenu_version=14.0.0-rc.2

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
