name: publish

on:
  workflow_dispatch:
    inputs:
      title:
        description: "The title for the release"
        required: true
        type: string
      previous_tag:
        description: "The previous git tag to use for generating the changelog"
        required: true
        type: string
      version:
        description: "The new version for the release"
        required: true
        type: string
      game_versions:
        description: "The supported Minecraft versions for the release"
        required: true
        type: string
      publish_common:
        description: "Publish for Common"
        type: boolean
        default: true
      publish_neoforge:
        description: "Publish for NeoForge"
        type: boolean
        default: true
      publish_fabric:
        description: "Publish for Fabric"
        type: boolean
        default: true
      publish_github:
        description: "Publish to GitHub Releases"
        type: boolean
        default: true
      publish_modrinth:
        description: "Publish to Modrinth"
        type: boolean
        default: true
      publish_curseforge:
        description: "Publish to CurseForge"
        type: boolean
        default: true


jobs:
  call-build-workflow:
    permissions:
      contents: read
    uses: "./.github/workflows/build.yml"

  publish:
    needs: call-build-workflow
    runs-on: ubuntu-latest
    env:
      changelog: '**Full Changelog**: https://github.com/thomasglasser/Sherds-API/compare/'
    permissions:
      contents: write
    strategy:
      matrix:
        loader: [ common, neoforge, fabric ]
        website: [ modrinth, curseforge, github_release ]
    name: ${{ matrix.website }} (${{ matrix.loader }})

    steps:
      - name: Download mod artifact
        uses: actions/download-artifact@v4
        continue-on-error: false
        with:
          name: Sherds API

      - name: Publish Github Release
        uses: Kir-Antipov/mc-publish@v3.3
        continue-on-error: true
        if: inputs.publish_github && matrix.website == 'github_release' && matrix.loader == 'common'
        with:
          name: &name ${{ inputs.title }}
          version: &version ${{ inputs.version }}
          changelog: &changelog ${{ env.changelog }}${{ inputs.previous_tag }}...${{ inputs.game_versions }}-${{ inputs.version }}
          java: &java Java 25
          game-versions: &game-versions |
            ${{ inputs.game_versions }}
          files: |
            ${{ inputs.publish_common && 'common/build/libs/!(*-@(dev|sources|javadoc)).jar' || '' }}
            ${{ inputs.publish_common && 'common/build/libs/*-@(dev|sources|javadocs).jar' || '' }}
            ${{ inputs.publish_neoforge && 'neoforge/build/libs/!(*-@(dev|sources|javadoc)).jar' || '' }}
            ${{ inputs.publish_neoforge && 'neoforge/build/libs/*-@(dev|sources|javadocs).jar' || '' }}
            ${{ inputs.publish_fabric && 'fabric/build/libs/!(*-@(dev|sources|javadoc)).jar' || '' }}
            ${{ inputs.publish_fabric && 'fabric/build/libs/*-@(dev|sources|javadocs).jar' || '' }}
          github-tag: ${{ inputs.game_versions }}-${{ inputs.version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Modrinth Release
        uses: Kir-Antipov/mc-publish@v3.3
        continue-on-error: true
        if: matrix.website == 'modrinth' && inputs.publish_modrinth && ((matrix.loader == 'neoforge' && inputs.publish_neoforge) || (matrix.loader == 'fabric' && inputs.publish_fabric))
        with:
          name: *name
          version: *version
          changelog: *changelog
          java: *java
          game-versions: *game-versions
          files: |
            ${{ matrix.loader }}/build/libs/!(*-@(dev|sources|javadoc)).jar
            ${{ matrix.loader }}/build/libs/*-@(dev|sources|javadoc).jar
          modrinth-id: sherdsapi
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

      - name: Publish Curseforge Release
        uses: Kir-Antipov/mc-publish@v3.3
        continue-on-error: true
        if: matrix.website == 'curseforge' && inputs.publish_curseforge && ((matrix.loader == 'neoforge' && inputs.publish_neoforge) || (matrix.loader == 'fabric' && inputs.publish_fabric))
        with:
          name: *name
          version: *version
          changelog: *changelog
          java: *java
          game-versions: *game-versions
          files: |
            ${{ matrix.loader }}/build/libs/!(*-@(dev|sources|javadoc)).jar
            ${{ matrix.loader }}/build/libs/*-@(dev|sources|javadocs).jar
          curseforge-id: 847583
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
